name: server
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - django
  - pip:
    # base
    - numpy
    - pydantic
    
    # postgres for python and django
    - "psycopg[binary]"
    # pgvector for python
    - pgvector
    
    # nlp packages for main functionality
    - ollama
    - langchain
    - langchain-community
  
    - pypdf
    
    # for django to run background tasks
    - celery[redis]