# Generated by Django 5.1.1 on 2024-09-27 18:09

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('doc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('doc_name', models.CharField(max_length=100)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('size', models.IntegerField(default=0)),
                ('embedding_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContextDocs',
            fields=[
                ('cd_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('doc_context', models.CharField(max_length=500)),
                ('embedded_vector', pgvector.django.vector.VectorField(dimensions=4096)),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbox.documents')),
            ],
        ),
    ]
