# Generated by Django 5.1.1 on 2024-09-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContextDocs',
            fields=[
                ('cd_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('doc_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('doc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('doc_name', models.CharField(max_length=100)),
            ],
        ),
    ]
