# Generated by Django 5.1.1 on 2024-09-25 16:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbox", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documents",
            name="size",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="documents",
            name="upload_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
