services:

  # Postgres SQL DB and tool
  pgdb:
    image: pgvector/pgvector:pg16
    container_name: pgdb-container
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdb-data:/var/lib/postgresql/data
      - ./database/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  # Redis Broker Cache
  broker:
    image: redis:latest
    container_name: redis-broker-container
    ports:
      - 6379:6379
    volumes:
      - redis-broker-data:/data
    environment: 
      REDIS_PASSWORD: secret
  
  # Model Host
  llm:
    build: 
      context: models/.
    container_name: llm-container
    ports:
      - 11434:11434

  # # Web Server
  # server:
  #   build: 
  #     context: server/.
  #   container_name: web-server-container
  #   environment:
  #     DJANGO_SUPERUSER_USERNAME: admin
  #     DJANGO_SUPERUSER_PASSWORD: admin
  #     DJANGO_SUPERUSER_EMAIL: admin@admin.com
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - ../server:/root/server
  #   depends_on:
  #     - pgdb
  #     - broker
  #   working_dir: /root/server/
  #   entrypoint: ['./start.sh']



  # # DB tools
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: pgadmin-container
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
  #     PGADMIN_DEFAULT_PASSWORD: temppass
  #     PGADMIN_LISTEN_PORT: 80
  #   ports:
  #     - 15432:80
  #   volumes:
  #     - pg-admin-data:/var/lib/pgadmin
  #   depends_on:
  #     - pgdb
  
  # redis-insight:
  #   image: redis/redisinsight:latest
  #   container_name: redis-insight-container
  #   restart: always
  #   ports:
  #     - "5540:5540"
  #   volumes:
  #     - redis-insight-data:/data
  #   depends_on:
  #     - broker



volumes:
 pgdb-data:
 pg-admin-data:
 redis-broker-data:
 redis-insight-data: