services:

  pgdb:
    image: pgvector/pgvector:pg16
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ../database/pgdb:/var/lib/postgresql/data
      - ./database/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: temppass
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - ../database/pgadmin:/var/lib/pgadmin
    depends_on:
      - pgdb

  # server:
  #   build: 
  #     context: server/.
  #   container_name: server-container
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - ../server:/root/server
  #   entrypoint: ['conda', 'run', '-n', 'server', 'python', '/root/server/manage.py', 'runserver', '0.0.0.0:8000']